name: nfc_manager_example
description: Demonstrates how to use the nfc_manager plugin.
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  nfc_manager:
    path: ../

flutter:
  uses-material-design: true

