name: nfc_manager
description: A Flutter plugin to use NFC. Supported on both Android and iOS.
version: 0.5.1
author: Naoki Okada <naoki.okada@hotmail.com>
homepage: https://github.com/okadan/flutter_nfc_manager.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.nfc_manager
    pluginClass: NfcManagerPlugin
