name: nfc_manager
description: A Flutter plugin to manage the NFC features. Supported on both Android and iOS.
version: 1.3.2+3
homepage: https://github.com/okadan/flutter-nfc-manager

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.nfc_manager
        pluginClass: NfcManagerPlugin
      ios:
        pluginClass: NfcManagerPlugin
